[read_ini.py]: [INFO] [2021-07-05 16:57:40] line:28->>加载 E:\My_code\UIAutoTest\config\appcfg.ini 文件......
[remote_connection.py]: [INFO] [2021-07-05 16:57:41] line:117->>Could not connect to port 4723 on host 192.168.1.5
[remote_connection.py]: [INFO] [2021-07-05 16:57:41] line:136->>Could not get IP address for host: 192.168.1.5
[connectionpool.py]: [WARNING] [2021-07-05 16:58:02] line:781->>Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x033027F0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',)': /wd/hub/session
[connectionpool.py]: [WARNING] [2021-07-05 16:58:23] line:781->>Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03302950>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',)': /wd/hub/session
[connectionpool.py]: [WARNING] [2021-07-05 16:58:44] line:781->>Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x032E8A70>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',)': /wd/hub/session
